/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBenchRouteImport } from './routes/api/bench'
import { Route as ApiRuntimeStatusRouteImport } from './routes/api/runtime-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBenchRoute = ApiBenchRouteImport.update({
  id: '/api/bench',
  path: '/api/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeStatusRoute = ApiRuntimeStatusRouteImport.update({
  id: '/api/runtime-status',
  path: '/api/runtime-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bench': typeof ApiBenchRoute
  '/api/runtime-status': typeof ApiRuntimeStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bench': typeof ApiBenchRoute
  '/api/runtime-status': typeof ApiRuntimeStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bench': typeof ApiBenchRoute
  '/api/runtime-status': typeof ApiRuntimeStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/bench' | '/api/runtime-status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/bench' | '/api/runtime-status'
  id: '__root__' | '/' | '/api/bench' | '/api/runtime-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBenchRoute: typeof ApiBenchRoute
  ApiRuntimeStatusRoute: typeof ApiRuntimeStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bench': {
      id: '/api/bench'
      path: '/api/bench'
      fullPath: '/api/bench'
      preLoaderRoute: typeof ApiBenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime-status': {
      id: '/api/runtime-status'
      path: '/api/runtime-status'
      fullPath: '/api/runtime-status'
      preLoaderRoute: typeof ApiRuntimeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBenchRoute: ApiBenchRoute,
  ApiRuntimeStatusRoute: ApiRuntimeStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
